import { useEffect, useMemo, useState } from "react";
import AppHeader from "@/components/AppHeader";
import AdminNav from "@/components/AdminNav";
import { useAdminGuard } from "@/hooks/useAdminGuard";
import { supabase } from "@/integrations/supabase/client";
import { Loader2, Users, MessageCircle, CreditCard, Crown } from "lucide-react";

type EventRow = { event_name: string; created_at: string };
export default function AdminOverview() {
  const { authLoading, isAdmin } = useAdminGuard();
  const [loading, setLoading] = useState(true);
  const [days, setDays] = useState(30);
  const [data, setData] = useState({ events: [] as EventRow[], leads: 0, pending: 0, active: 0, users: 0 });
  useEffect(() => { if (!isAdmin) return; (async () => { setLoading(true); const since = new Date(Date.now() - days * 86400000).toISOString(); const [events, leads, pending, active, users] = await Promise.all([supabase.from("analytics_events").select("event_name,created_at").gte("created_at", since), supabase.from("leads").select("id", { count: "exact", head: true }).gte("created_at", since), supabase.from("payment_requests").select("id", { count: "exact", head: true }).eq("status", "pending"), supabase.from("subscriptions").select("id", { count: "exact", head: true }).eq("status", "active").gt("expires_at", new Date().toISOString()), supabase.from("profiles").select("id", { count: "exact", head: true })]); setData({ events: (events.data ?? []) as EventRow[], leads: leads.count ?? 0, pending: pending.count ?? 0, active: active.count ?? 0, users: users.count ?? 0 }); setLoading(false); })(); }, [isAdmin, days]);
  const counts = useMemo(() => Object.fromEntries(["try_free_click","app_started","google_sign_in","free_export","lead_submitted","payment_opened","payment_submitted"].map((name) => [name, data.events.filter((e) => e.event_name === name).length])), [data.events]);
  if (authLoading || isAdmin === null) return <div className="min-h-screen grid place-items-center"><Loader2 className="h-6 w-6 animate-spin" /></div>;
  if (!isAdmin) return null;
  const cards = [{ label: "Registered users", value: data.users, icon: Users }, { label: `Leads · ${days} days`, value: data.leads, icon: MessageCircle }, { label: "Pending payments", value: data.pending, icon: CreditCard }, { label: "Active Pro", value: data.active, icon: Crown }];
  return <div className="min-h-screen bg-background"><AppHeader /><main className="max-w-6xl mx-auto px-4 py-8"><div className="flex items-center justify-between gap-4 mb-4"><h1 className="text-2xl font-bold">Business overview</h1><select value={days} onChange={(e) => setDays(Number(e.target.value))} className="h-9 rounded-md border bg-background px-3 text-sm"><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option></select></div><AdminNav />{loading ? <div className="py-20 grid place-items-center"><Loader2 className="h-6 w-6 animate-spin" /></div> : <><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{cards.map(({ label, value, icon: Icon }) => <div key={label} className="rounded-lg border bg-card p-5"><Icon className="h-5 w-5 text-primary" /><div className="text-3xl font-bold mt-3">{value}</div><div className="text-sm text-muted-foreground mt-1">{label}</div></div>)}</div><section className="mt-6"><h2 className="text-lg font-semibold mb-3">Tracked conversion funnel</h2><div className="rounded-lg border bg-card overflow-x-auto"><div className="grid grid-cols-7 min-w-[760px]">{[["Try free",counts.try_free_click],["App starts",counts.app_started],["Google sign-ins",counts.google_sign_in],["Free exports",counts.free_export],["Leads",counts.lead_submitted],["Payment opened",counts.payment_opened],["Submitted",counts.payment_submitted]].map(([label,value], i) => <div key={String(label)} className="p-4 border-r last:border-r-0"><div className="text-2xl font-bold">{value}</div><div className="text-xs text-muted-foreground mt-1">{label}</div>{i > 0 && <div className="text-[11px] text-primary mt-2">{Number(counts.try_free_click) > 0 ? `${Math.round(Number(value) / Number(counts.try_free_click) * 100)}% of starts` : "Collecting data"}</div>}</div>)}</div></div><p className="text-xs text-muted-foreground mt-3">New event tracking starts from this release; earlier visitors are available in project analytics.</p></section></>}</main></div>;
}
